# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace    # Removes trailing whitespace at the end of lines
    -   id: end-of-file-fixer     # Ensures files end with a newline
    -   id: check-yaml            # Validates yaml files for syntax errors
    -   id: check-added-large-files # Prevents committing large files (>500KB by default)

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.3
    hooks:
    -   id: ruff                   # Runs Ruff linter with auto-fixes
        args: [--fix]
    -   id: ruff-format           # Runs Ruff formatter to ensure consistent code style
