name: venv
dependencies:
  - python=3.9
  - pip
  - pip:
    - torch==2.5.1
    - typer==0.15.1
    - fastapi==0.115.6
    - uvicorn==0.34.0
    - transformers==4.30.2 
    - invoke==2.2.0
    - pre-commit==3.5.0
    - pytest==7.4.3
    - coverage==7.6.9
    - ruff==0.1.3
    - mkdocs==1.5.3
    - mkdocs-material==9.4.6
    - mkdocstrings-python==1.12.2
    - dvc==2.8.3
  - pytorch
  - torchvision
  - torchaudio
  - cpuonly
  - -c pytorch