_wandb:
    value:
        cli_version: 0.19.3
        m: []
        python_version: 3.12.6
        t:
            "1":
                - 1
                - 2
                - 3
                - 5
                - 11
                - 41
                - 49
                - 50
                - 53
                - 55
                - 71
                - 105
            "2":
                - 1
                - 2
                - 3
                - 5
                - 11
                - 41
                - 49
                - 50
                - 53
                - 55
                - 71
                - 105
            "3":
                - 14
                - 16
                - 23
                - 55
            "4": 3.12.6
            "5": 0.19.3
            "6": 4.48.0
            "8":
                - 2
                - 3
                - 5
            "12": 0.19.3
            "13": windows-amd64
batch_size:
    value: 8
epochs:
    value: 2
learning_rate:
    value: 1e-05
model_name:
    value: albert-base-v2
num_labels:
    value: 3
