name: DVC and Model Registry Workflow

on:
  push:
    branches:
      - main
    paths:
      - 'ddata/processed/**'
      - '**/*.dvc'
      - '.dvc/**'
      - 'models/**'
  pull_request:
    branches:
      - main
    paths:
      - 'data/processed/**'
      - '**/*.dvc'
      - '.dvc/**'
      - 'models/**'

jobs:
  dataset_statistics:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'
        cache-dependency-path: setup.py

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install -r requirements_dev.txt
        pip list

    - name: Pull data
      run: dvc pull --no-run-cache

    - name: Check data statistics & generate report
      run: |
        python src/sentiment_analysis/data.py > data_statistics.md
        echo '![](./train_label_distribution.png "Train label distribution")' >> data_statistics.md
        echo '![](./test_label_distribution.png "Test label distribution")' >> data_statistics.md

    - name: Setup cml
      uses: iterative/setup-cml@v2

    - name: Comment on PR
      env:
        REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        cml comment create data_statistics.md --watermark-title="Data Checker"
