name: DVC and Model Registry Workflow

on:
  push:
    branches:
      - main
    paths:
      - 'data/**'
      - '**/*.dvc'
      - '.dvc/**'
      - 'models/**'
  pull_request:
    branches:
      - main
    paths:
      - 'data/**'
      - '**/*.dvc'
      - '.dvc/**'
      - 'models/**'

jobs:
  dataset_statistics:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'
        cache-dependency-path: setup.py

    - name: Install dependencies
      run: |
        pip install -r MLOpsProject/requirements.txt
        pip install -r MLOpsProject/requirements_dev.txt

    - name: Authenticate with GCP
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Pull data from DVC remote
      run: |
        dvc pull --no-run-cache -v

    - name: Cache DVC remote data
      uses: actions/cache@v3
      with:
        path: ~/.cache/dvc
        key: ${{ runner.os }}-dvc-${{ github.ref }}
        restore-keys: |
          ${{ runner.os }}-dvc-

    - name: Check data statistics & generate report
      run: |
        python MLOpsProject/src/sentiment_analysis/data.py dataset-statistics > data_statistics.md
        echo '![](./train_label_distribution.png "Train label distribution")' >> data_statistics.md
        echo '![](./test_label_distribution.png "Test label distribution")' >> data_statistics.md

    - name: Cleanup DVC cache
      run: |
        dvc gc --workspace --cloud

    - name: Setup CML
      uses: iterative/setup-cml@v2

    - name: Post comment on PR with statistics
      env:
        REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        cml comment create data_statistics.md --watermark-title="Data Checker"
