name: Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run_tests:
    strategy:
      fail-fast: false
    matrix:
      operating-system: ["windows-latest"]
      python-version: ["3.12", "3.11"]
      pytorch-version: ["2.2.2"]
      
    runs-on: ${{ matrix.operating-system }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.pip-cache.outputs.dir }}
          key: cached_test-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-py-${{ matrix.python-version }}-torch-${{ matrix.pytorch-version }}-
            ${{ runner.os }}-py-${{ matrix.python-version }}-


      - name: Install dependencies
        run: |
          python -m pip install -U pip setuptools wheel
          pip install -r MLOpsProject/requirements.txt

      - name: Lint with flake8
        run: |
          flake8 MLOpsProject/

      - uses: iterative/setup-dvc@v1
      - name: Get data
        run: dvc pull

      - name: Test with pytest
        run: |
          pip install pytest coverage
          coverage run -m pytest -v
          coverage report -i
