name: Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: ["windows-latest", "macos-latest"]
        python-version: ["3.12", "3.11"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          cache-dependency-path: setup.py

      - name: Install dependencies
        run: |
          python -m pip install -U pip setuptools wheel
          pip install -r MLOpsProject/requirements.txt
          pip install -r MLOpsProject/requirements_dev.txt
          pip install ruff
          pip list

      - name: Run Ruff format
        run: |
          ruff format MLOpsProject/

      - name: Run Ruff check
        run: |
          ruff check MLOpsProject/

      - name: Run tests & coverage
        run: |
          coverage run --rcfile = MLOpsProject/.coveragerc -m pytest MLOpsProject/tests
          coverage report -m
