name: Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system: ["windows-latest"]
        python-version: ["3.12", "3.11"]
        pytorch-version: ["2.2.2"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache Python dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-py-${{ matrix.python-version }}-torch-${{ matrix.pytorch-version }}-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-py-${{ matrix.python-version }}-torch-${{ matrix.pytorch-version }}-
            ${{ runner.os }}-py-${{ matrix.python-version }}-

      - name: Install dependencies
        run: |
          python -m pip install -U pip setuptools wheel
          pip install -r MLOpsProject/requirements.txt
          pip install torch==${{ matrix.pytorch-version }}
          pip list

      - name: Run tests & coverage
        run: |
          coverage run -m pytest MLOpsProject/tests/
          coverage report -m

      - name: Upload coverage report (optional)
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: .coverage
